version: "3.7"

services:
    frontend:
        container_name: frontend
        build: .
        volumes:
            - "./:/app"
            - "/app/node_modules"
        ports:
            - 3000:3000
        command: npm start
