export enum FileStorageAttachApiType {
    NEWS_IMAGE = "NewsImage",
    NEWS_VIDEO = "NewsVideo",
    PROFILE_AVATAR = "Avatar",
    SCENE_MARKER = "SceneTrackerImage",
    SCENE_AUDIO = "MarkerAudio",
    SCENE_AR_OBJECT = "MarkerArObject",
    SCENE_UI_BUTTON_IMAGE = "ButtonImage",
    SCENE_ASSET_IOS = "AssetBundleIos",
    SCENE_ASSET_ANDROID = "AssetBundleAndroid",
    SCENE_ASSET_WEBGL = "AssetBundleWebGL",
    PRODUCT_MODEL = "Product3dModel",
    PRODUCT_IMAGE = "ProductImage",
    BRANDING_LOGO = "LoadingScreenLogo",
    BRANDING_BACKGROUND = "LoadingScreenBackground",
    BRANDING_TEMPLATE_LOGO = "LoadingScreenTemplateLogo",
    BRANDING_TEMPLATE_BACKGROUND = "LoadingScreenTemplateBackground",
}
